version: '3.8'

services:
  mysqldb:
    container_name: HREA-DB
    image: mysql:8.0.22
    restart: unless-stopped
    env_file:
      - ./docker.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DB
      - TZ=Asia/Bangkok  # Set the timezone
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
      ]
  be: 
    container_name: HERA-BE
    image: ngthanhtuung/hrea-capstone:latest
    restart: unless-stopped
    env_file:
      - ./docker.env
    depends_on:
      - mysqldb
    ports:
      - $PORT:$PORT  # Replace with the actual environment variable or specific port number
      - "3006:3006"  # Ensure this matches the previous mapping
    stdin_open: true
    tty: true
volumes:
  db:
    name: db