version: '3.8'

services:
  mysqldb:
    container_name: HREA-DB
    platform: linux/x86_64
    image: mysql:5.7
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DB
    ports:
      - $MYSQL_PORT:3306
    volumes:
      - db:/var/lib/mysql
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
      ]
volumes:
  db: